--  Configuration for dwm generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Dwm_Config is
   pragma Pure;

   Crate_Version : constant String := "6.8.0";
   Crate_Name : constant String := "dwm";

   Alire_Host_OS : constant String := "linux";

   Alire_Host_Arch : constant String := "x86_64";

   Alire_Host_Distro : constant String := "fedora";

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := development;

end Dwm_Config;
