/* Configuration for dwm generated by Alire */
#ifndef DWM_CONFIG_H
#define DWM_CONFIG_H

#define CRATE_VERSION "6.8.0"
#define CRATE_NAME "dwm"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "fedora"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
